# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

schedules:
- cron: "59 23 * * 7/2"
  displayName: midnight access change every 2 weeks
  branches:
    include:
    - master
  always: true

steps:   
- task: CmdLine@2
  inputs:
    script: |
      curl -X PUT -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $(token)" https://api.github.com/orgs/permissionsspike/teams/developersspike/repos/permissionsspike/permissionspikerepo -D '{"permission":"pull"}' -i
