# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

schedules:
- cron: "14 12 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

steps:   
- task: CmdLine@2
  inputs:
    script: |
      curl \
                  -X PUT \
                  -H "Accept: application/vnd.github.v3+json" \
                  -H "Authorization: token 15fe08144779a80bb855045b75441c44b62d8c82" \
                  https://api.github.com/organizations/73760643/team/4229200/repos/PermissionsSpike/PermissionSpikeRepo \
                  -d '{"permission":"pull"}'
